#!/bin/bash
# unpack and copy downloaded zip files from jamendo
# note: try to use ogg via torrent instead if possible

DOWNLOAD_DIR=$HOME/Downloads/
MUSIC_DIR=/home/shared/music/

for i in ${DOWNLOAD_DIR}*www.jamendo.com*.zip; do
  TARGET="${i#$DOWNLOAD_DIR}"
  if [[ $TARGET = "*www.jamendo.com*.zip" ]]; then
    echo "no jamendo archives found" >&2
    break
  fi
  TARGET="$MUSIC_DIR/${TARGET%.zip}"
  [[ -d "$TARGET" ]] && continue
  mkdir "$TARGET" && \
  unzip "$i" -d "$TARGET" && \
  rm "$i"
done

mpc update
