#!/bin/bash
# dirty cleaning of $HOME/tmp dir

#DEBUG=echo

# leave files from this and last year alone
LIMIT_YEAR=$(( $(date +'%Y') - 1))

get_year() {
  stat -c %y "$1" | cut -d '-' -f 1
}

for f in *; do
  # ommit directories
  [[ -d $f ]] && continue

  YEAR=$(get_year $f) 
  if [[ $YEAR -ge $LIMIT_YEAR ]]; then
    continue
  fi
  if [[ ! -d $YEAR ]]; then
    mkdir $YEAR
    YEARS="$YEARS $YEAR"
  fi

  $DEBUG mv $f $YEAR
done

for i in $YEARS; do
  touch -t "${i}01010000" $i
done
